basePath: /api/v1
info:
  contact: {}
  description: Swagger API for Golang Admin API.
  license: {}
  title: Go Admin API Documents
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
